# Generated by Django 5.2.7 on 2025-10-05 17:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_image_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_description', models.TextField()),
                ('start_price', models.DecimalField(decimal_places=2, help_text='The initial bidding price.', max_digits=10)),
                ('current_bid', models.DecimalField(blank=True, decimal_places=2, help_text='The current highest bid. Initially can be same as start price.', max_digits=10, null=True)),
                ('auction_start_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('auction_end_date_time', models.DateTimeField()),
                ('main_image', models.ImageField(upload_to='products/main/')),
                ('gallery_images', models.JSONField(blank=True, help_text='List of paths to gallery images', null=True)),
                ('sku', models.CharField(help_text='Stock Keeping Unit', max_length=100, unique=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kilograms (e.g., 5.25)', max_digits=6, null=True)),
                ('dimensions', models.CharField(blank=True, help_text='Dimensions as L x W x H cm', max_length=100)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.category')),
            ],
        ),
    ]
