# Generated by Django 5.2.7 on 2025-10-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
