# Generated by Django 5.2.7 on 2025-10-05 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_product_gallery_images_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
