# Generated by Django 5.2.4 on 2025-10-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
