# Generated by Django 5.2.4 on 2025-10-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_review_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_description',
            field=models.TextField(default=''),
        ),
    ]
