# Generated by Django 5.2.4 on 2025-10-12 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_bidding'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bidding',
            unique_together=set(),
        ),
    ]
